### ISSUE TITLE
Build make file under windows

### ISSUE THREAD

**Issue by Johndirr** [fsinapsi/ffmatch#6]
Hi,

I just tried to compile this under windows. Make is issuing an error about not being able to find trcp.
I never heard about tin and trp files. Can you please give some information on how to run/install this?

Thank you

**Comment by fsinapsi** [comment]
You can find a compiled version here:

http://fsinapsi.altervista.org

You can also compile it, but you have to compile trpc first, following the instructions in the file installare-treep-in-sistemi-windows.7z
(only in Italian, sorry, but you can translate 00leggimi.txt into English with an online translator)

In short, if you want to compile, you need to install msys2:

https://www.msys2.org/

(Download the installer: msys2-x86_64-20240113.exe)

Then copy "installa-pacchetti.sh" and "iup-3.31.tar.gz" in c:\msys64

Launch "ucrt64"

pacman -Syu
(one or more times, until it is fully updated)

cd /
sh installa-pacchetti.sh
tar xzf iup-3.31.tar.gz
rm installa-pacchetti.sh iup-3.31.tar.gz
cd
git clone https://github.com/fsinapsi/TreeP
cd TreeP
make bootstrap

trpc -v

**Comment by Johndirr** [comment]
Ah, now I understand. Thank you. Ill go with the prebuild exe then :)
